// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jbnqmplyxmpehbwkejnv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpibnFtcGx5eG1wZWhid2tlam52Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3Njk0NjAsImV4cCI6MjA2ODM0NTQ2MH0.MxY4hX0KWqVFXWkzF2MWrNJ3PWbMpLXdqJunpGP8EA8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});